@startuml Diagrama_arquitectura 
title Diagrama de Arquitectura Web 
actor Cliente

node "Servidor Web" {
    component "Frontend (HTML,CSS, JS)" AS Frontend
    component "API Flask (Backend)" as API 

}

node "Servidor Base de Datos" {
    database "MySQL" as BD
}

Cliente --> Frontend
Frontend --> API 
API --> BD
@enduml